-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 09:25:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema datvexekhach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datvexekhach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datvexekhach` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `datvexekhach` ;

-- -----------------------------------------------------
-- Table `datvexekhach`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`USER` (
  `Name` VARCHAR(100) NOT NULL,
  `Phone Num` VARCHAR(45) NOT NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `SEX` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `USERacc` VARCHAR(45) NULL DEFAULT NULL,
  `USERpassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Phone Num`),
  UNIQUE INDEX `Phone Num_UNIQUE` (`Phone Num` ASC) VISIBLE,
  UNIQUE INDEX `USERacc_UNIQUE` (`USERacc` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`BILL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`BILL` (
  `BILL No` INT NOT NULL,
  `Time` DATETIME NOT NULL,
  `Price` INT NOT NULL,
  `User Phone Num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BILL No`, `User Phone Num`),
  INDEX `fk_BILL_USER1_idx` (`User Phone Num` ASC) VISIBLE,
  CONSTRAINT `fk_BILL_USER1`
    FOREIGN KEY (`User Phone Num`)
    REFERENCES `datvexekhach`.`USER` (`Phone Num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`BUS STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`BUS STATION` (
  `BName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`BName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`ROUTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`ROUTE` (
  `ROUTE Num` INT NOT NULL,
  `FROM` VARCHAR(50) NULL DEFAULT NULL,
  `Drop off point` VARCHAR(45) NULL DEFAULT NULL,
  `BUS STATION_BName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ROUTE Num`, `BUS STATION_BName`),
  INDEX `fk_ROUTE_BUS STATION_idx` (`BUS STATION_BName` ASC) VISIBLE,
  CONSTRAINT `fk_ROUTE_BUS STATION`
    FOREIGN KEY (`BUS STATION_BName`)
    REFERENCES `datvexekhach`.`BUS STATION` (`BName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`TRIP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`TRIP` (
  `TRIP No` INT NOT NULL,
  `Time` DATETIME NOT NULL,
  `Num of seat` INT NOT NULL,
  `TRIP Name` VARCHAR(45) NOT NULL,
  `ROUTE Num` INT NOT NULL,
  PRIMARY KEY (`TRIP No`, `ROUTE Num`),
  INDEX `fk_TRIP_ROUTE1_idx` (`ROUTE Num` ASC) VISIBLE,
  CONSTRAINT `fk_TRIP_ROUTE1`
    FOREIGN KEY (`ROUTE Num`)
    REFERENCES `datvexekhach`.`ROUTE` (`ROUTE Num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`COACH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`COACH` (
  `License plates` VARCHAR(20) NOT NULL,
  `COACHName` VARCHAR(45) NOT NULL,
  `TripNo` INT NOT NULL,
  PRIMARY KEY (`License plates`, `TripNo`),
  INDEX `fk_COACH_TRIP1_idx` (`TripNo` ASC) VISIBLE,
  CONSTRAINT `fk_COACH_TRIP1`
    FOREIGN KEY (`TripNo`)
    REFERENCES `datvexekhach`.`TRIP` (`TRIP No`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`TICKET` (
  `TICKET NO` INT NOT NULL,
  `Info` VARCHAR(45) NULL DEFAULT NULL,
  `Price` INT NOT NULL,
  `Status` TINYINT NOT NULL,
  `TRIP No` INT NOT NULL,
  `SEATNO` INT NOT NULL,
  PRIMARY KEY (`TICKET NO`, `TRIP No`),
  INDEX `fk_TICKET_TRIP1_idx` (`TRIP No` ASC) VISIBLE,
  CONSTRAINT `fk_TICKET_TRIP1`
    FOREIGN KEY (`TRIP No`)
    REFERENCES `datvexekhach`.`TRIP` (`TRIP No`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`ORDER` (
  `TICKET NO` INT NOT NULL,
  `USER_Phone Num` VARCHAR(45) NOT NULL,
  `TimeBuy` DATETIME NOT NULL,
  PRIMARY KEY (`TICKET NO`, `USER_Phone Num`),
  INDEX `fk_TICKET_has_USER_USER1_idx` (`USER_Phone Num` ASC) VISIBLE,
  INDEX `fk_TICKET_has_USER_TICKET1_idx` (`TICKET NO` ASC) VISIBLE,
  CONSTRAINT `fk_TICKET_has_USER_TICKET1`
    FOREIGN KEY (`TICKET NO`)
    REFERENCES `datvexekhach`.`TICKET` (`TICKET NO`),
  CONSTRAINT `fk_TICKET_has_USER_USER1`
    FOREIGN KEY (`USER_Phone Num`)
    REFERENCES `datvexekhach`.`USER` (`Phone Num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- MySQL Script generated by MySQL Workbench
-- Sun Apr 25 09:01:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema datvexekhach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema datvexekhach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `datvexekhach` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `datvexekhach` ;

-- -----------------------------------------------------
-- Table `datvexekhach`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`USER` (
  `Name` VARCHAR(100) NOT NULL,
  `Phone Num` VARCHAR(45) NOT NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `SEX` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `USERacc` VARCHAR(45) NULL DEFAULT NULL,
  `USERpassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Phone Num`),
  UNIQUE INDEX `Phone Num_UNIQUE` (`Phone Num` ASC) VISIBLE,
  UNIQUE INDEX `USERacc_UNIQUE` (`USERacc` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`BILL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`BILL` (
  `BILL No` INT NOT NULL,
  `Time` DATETIME NOT NULL,
  `Price` INT NOT NULL,
  `User Phone Num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BILL No`, `User Phone Num`),
  INDEX `fk_BILL_USER1_idx` (`User Phone Num` ASC) VISIBLE,
  CONSTRAINT `fk_BILL_USER1`
    FOREIGN KEY (`User Phone Num`)
    REFERENCES `datvexekhach`.`USER` (`Phone Num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`BUS STATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`BUS STATION` (
  `BName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`BName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`ROUTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`ROUTE` (
  `ROUTE Num` INT NOT NULL,
  `FROM` VARCHAR(50) NULL DEFAULT NULL,
  `Drop off point` VARCHAR(45) NULL DEFAULT NULL,
  `BUS STATION_BName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ROUTE Num`, `BUS STATION_BName`),
  INDEX `fk_ROUTE_BUS STATION_idx` (`BUS STATION_BName` ASC) VISIBLE,
  CONSTRAINT `fk_ROUTE_BUS STATION`
    FOREIGN KEY (`BUS STATION_BName`)
    REFERENCES `datvexekhach`.`BUS STATION` (`BName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`TRIP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`TRIP` (
  `TRIP No` INT NOT NULL,
  `Time` DATETIME NOT NULL,
  `Num of seat` INT NOT NULL,
  `TRIP Name` VARCHAR(45) NOT NULL,
  `ROUTE Num` INT NOT NULL,
  PRIMARY KEY (`TRIP No`, `ROUTE Num`),
  INDEX `fk_TRIP_ROUTE1_idx` (`ROUTE Num` ASC) VISIBLE,
  CONSTRAINT `fk_TRIP_ROUTE1`
    FOREIGN KEY (`ROUTE Num`)
    REFERENCES `datvexekhach`.`ROUTE` (`ROUTE Num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`COACH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`COACH` (
  `License plates` VARCHAR(20) NOT NULL,
  `COACHName` VARCHAR(45) NOT NULL,
  `TripNo` INT NOT NULL,
  PRIMARY KEY (`License plates`, `TripNo`),
  INDEX `fk_COACH_TRIP1_idx` (`TripNo` ASC) VISIBLE,
  CONSTRAINT `fk_COACH_TRIP1`
    FOREIGN KEY (`TripNo`)
    REFERENCES `datvexekhach`.`TRIP` (`TRIP No`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`TICKET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`TICKET` (
  `TICKET NO` INT NOT NULL,
  `Info` VARCHAR(45) NULL DEFAULT NULL,
  `Price` INT NOT NULL,
  `Status` TINYINT NOT NULL,
  `TRIP No` INT NOT NULL,
  `SEATNO` INT NOT NULL,
  PRIMARY KEY (`TICKET NO`, `TRIP No`),
  INDEX `fk_TICKET_TRIP1_idx` (`TRIP No` ASC) VISIBLE,
  CONSTRAINT `fk_TICKET_TRIP1`
    FOREIGN KEY (`TRIP No`)
    REFERENCES `datvexekhach`.`TRIP` (`TRIP No`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `datvexekhach`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `datvexekhach`.`ORDER` (
  `TICKET NO` INT NOT NULL,
  `USER_Phone Num` VARCHAR(45) NOT NULL,
  `TimeBuy` DATETIME NOT NULL,
  PRIMARY KEY (`TICKET NO`, `USER_Phone Num`),
  INDEX `fk_TICKET_has_USER_USER1_idx` (`USER_Phone Num` ASC) VISIBLE,
  INDEX `fk_TICKET_has_USER_TICKET1_idx` (`TICKET NO` ASC) VISIBLE,
  CONSTRAINT `fk_TICKET_has_USER_TICKET1`
    FOREIGN KEY (`TICKET NO`)
    REFERENCES `datvexekhach`.`TICKET` (`TICKET NO`),
  CONSTRAINT `fk_TICKET_has_USER_USER1`
    FOREIGN KEY (`USER_Phone Num`)
    REFERENCES `datvexekhach`.`USER` (`Phone Num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;







INSERT INTO `datvexekhach`.`BUS STATION` (`BName`) VALUES ('Hà Nội');
INSERT INTO `datvexekhach`.`BUS STATION` (`BName`) VALUES ('Hưng Yên');
INSERT INTO `datvexekhach`.`BUS STATION` (`BName`) VALUES ('Nam Định');
INSERT INTO `datvexekhach`.`BUS STATION` (`BName`) VALUES ('Nghệ An');
INSERT INTO `datvexekhach`.`BUS STATION` (`BName`) VALUES ('Bắc Giang');


INSERT INTO `datvexekhach`.`ROUTE` (`ROUTE Num`, `FROM`, `Drop off point`, `BUS STATION_BName`) VALUES ('1', 'Hà Nội', 'Nghệ An', 'Hà Nội');
INSERT INTO `datvexekhach`.`ROUTE` (`ROUTE Num`, `FROM`, `Drop off point`, `BUS STATION_BName`) VALUES ('2', 'Hưng Yên', 'Hà Nội', 'Hưng Yên');
INSERT INTO `datvexekhach`.`ROUTE` (`ROUTE Num`, `FROM`, `Drop off point`, `BUS STATION_BName`) VALUES ('3', 'Bắc Giang', 'Nghệ An', 'Bắc Giang');

INSERT INTO `datvexekhach`.`TRIP` (`TRIP No`, `Time`, `Num of seat`, `ROUTE Num`) VALUES ('1', '2021-05-15 15:00:00', '40', '1');
INSERT INTO `datvexekhach`.`TRIP` (`TRIP No`, `Time`, `Num of seat`, `ROUTE Num`) VALUES ('2', '2021-05-15 18:00:00', '20', '1');
INSERT INTO `datvexekhach`.`TRIP` (`TRIP No`, `Time`, `Num of seat`, `ROUTE Num`) VALUES ('3', '2021-05-16 15:00:00', '30', '2');
INSERT INTO `datvexekhach`.`TRIP` (`TRIP No`, `Time`, `Num of seat`, `ROUTE Num`) VALUES ('4', '2021-05-18 15:00:00', '20', '3');

INSERT INTO `datvexekhach`.`COACH` (`License plates`, `COACHName`, `TripNo`) VALUES ('37B-11223', 'xe1', '01');
INSERT INTO `datvexekhach`.`COACH` (`License plates`, `COACHName`, `TripNo`) VALUES ('29B-22222', 'xe2', '02');
INSERT INTO `datvexekhach`.`COACH` (`License plates`, `COACHName`, `TripNo`) VALUES ('30B-12345', 'xe3', '03');
INSERT INTO `datvexekhach`.`COACH` (`License plates`, `COACHName`, `TripNo`) VALUES ('37B-88888', 'xe4', '01');


INSERT INTO `datvexekhach`.`TICKET` (`TICKET NO`, `Price`, `Status`, `TRIP No`, `SEATNO`) VALUES ('01', '100000', '1', '4', '30');
INSERT INTO `datvexekhach`.`TICKET` (`TICKET NO`, `Price`, `Status`, `TRIP No`, `SEATNO`) VALUES ('02', '500000', '1', '2', '10');
INSERT INTO `datvexekhach`.`TICKET` (`TICKET NO`, `Price`, `Status`, `TRIP No`, `SEATNO`) VALUES ('03', '250000', '1', '3', '2');


INSERT INTO `datvexekhach`.`USER` (`Name`, `Phone Num`, `SEX`, `Address`, `USERacc`, `USERpassword`) VALUES ('Nguyễn Văn Hải', '0112233444', 'Nam', 'Hưng Yên', 'haihy', '123456');
INSERT INTO `datvexekhach`.`USER` (`Name`, `Phone Num`, `SEX`, `Address`, `USERacc`, `USERpassword`) VALUES ('Nguyễn Trọng Đạt', '0888888888', 'Nam', 'Nghệ An', 'datntrong', '123456');
INSERT INTO `datvexekhach`.`USER` (`Name`, `Phone Num`, `SEX`, `Address`, `USERacc`, `USERpassword`) VALUES ('Vũ Mạnh Cường', '0123456789', 'Nam', 'Hà Nội', 'cuong', '123456');
INSERT INTO `datvexekhach`.`USER` (`Name`, `Phone Num`, `SEX`, `Address`, `USERacc`, `USERpassword`) VALUES ('Đặng Minh Hiếu', '01122334455', 'Nam', 'Nghệ An', 'hieu', '123456');


INSERT INTO `datvexekhach`.`ORDER` (`TICKET NO`, `USER_Phone Num`, `TimeBuy`) VALUES ('1', '0112233444', '2021-04-30 15:00:00');
INSERT INTO `datvexekhach`.`ORDER` (`TICKET NO`, `USER_Phone Num`, `TimeBuy`) VALUES ('2', '0112233444', '2021-04-28 10:00:00');
INSERT INTO `datvexekhach`.`ORDER` (`TICKET NO`, `USER_Phone Num`, `TimeBuy`) VALUES ('3', '0112233444', '2021-04-19 17:00:00');



INSERT INTO `datvexekhach`.`BILL` (`BILL No`, `Time`, `Price`, `User Phone Num`) VALUES ('1', '2021-04-30 15:00:00', '100000', '0112233444');
INSERT INTO `datvexekhach`.`BILL` (`BILL No`, `Time`, `Price`, `User Phone Num`) VALUES ('2', '2021-04-28 10:00:00', '500000', '0112233444');
INSERT INTO `datvexekhach`.`BILL` (`BILL No`, `Time`, `Price`, `User Phone Num`) VALUES ('3', '2021-04-19 17:00:00', '250000', '0112233444');







